In [166]:
import pandas as pd
import re 
from nltk.corpus import stopwords
from bs4 import BeautifulSoup
from nltk.stem import WordNetLemmatizer
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from nltk.tokenize import word_tokenize
import numpy as np
from tqdm import tqdm

In [104]:
df = pd.read_csv("all_kindle_review .csv")

In [105]:
df = df[["reviewText","rating"]]

In [106]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [107]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [108]:
df["rating"].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [109]:
df["rating"].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [110]:
df['rating'] = df["rating"].apply(lambda x:1 if x>3 else 0)
# 1 if rating is > 3 , 0 for rating <= 3

In [111]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       0
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       0
3  Aggie is Angela Lansbury who carries pocketboo...       0
4  I did not expect this type of book to be in li...       1

In [112]:
df['rating'].value_counts()

rating
0    6000
1    6000
Name: count, dtype: int64

In [113]:
df["reviewText"] = df["reviewText"].str.lower()

In [114]:
#removing special character
df['reviewText'] = df["reviewText"].apply(lambda x: re.sub('[^a-z A-Z 0-9]+'," ",x))
df['reviewText'] = df["reviewText"].apply(lambda x: " ".join([y for y in x.split() if y not in stopwords.words('english')]))
df['reviewText'] = df["reviewText"].apply(lambda x: BeautifulSoup(x,"html.parser").get_text())
df["reviewText"] = df["reviewText"].apply(lambda x: ' '.join(x.split())) #remove additional spaces..

In [115]:
df.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       0
1  great short read want put read one sitting sex...       1
2  start saying first four books expecting 34 con...       0
3  aggie angela lansbury carries pocketbooks inst...       0
4  expect type book library pleased find price right       1

In [116]:
wnl = WordNetLemmatizer()

In [ ]:
def lemmatize_words(text):
    return " ".join([wnl.lemmatize(word) for word in text.split()])

In [118]:
df["reviewText"] = df["reviewText"].apply(lambda x:lemmatize_words(x))

In [119]:
df.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       0
1  great short read want put read one sitting sex...       1
2  start saying first four book expecting 34 conc...       0
3  aggie angela lansbury carry pocketbook instead...       0
4  expect type book library pleased find price right       1

In [ ]:
X = df["reviewText"]
y = df["rating"]

In [121]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20)

In [122]:
#converting into vectors using BOW
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [123]:
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [124]:
mnb_bow = MultinomialNB().fit(X_train_bow,y_train)

In [169]:
y_pred_bow = mnb_bow.predict(X_test_bow)
print(accuracy_score(y_pred_bow,y_test))
print(confusion_matrix(y_pred_bow,y_test))
print(classification_report(y_pred_bow,y_test))

0.50125
[[354 345]
 [852 849]]
              precision    recall  f1-score   support

           0       0.29      0.51      0.37       699
           1       0.71      0.50      0.59      1701

    accuracy                           0.50      2400
   macro avg       0.50      0.50      0.48      2400
weighted avg       0.59      0.50      0.52      2400



In [126]:
mnb_tfidf = MultinomialNB().fit(X_train_tfidf,y_train)
y_pred_tfidf = mnb_tfidf.predict(X_test_tfidf)
print(accuracy_score(y_pred_tfidf,y_test))
print(confusion_matrix(y_pred_tfidf,y_test))
print(classification_report(y_pred_tfidf,y_test))

0.81125
[[995 254]
 [199 952]]
              precision    recall  f1-score   support

           0       0.83      0.80      0.81      1249
           1       0.79      0.83      0.81      1151

    accuracy                           0.81      2400
   macro avg       0.81      0.81      0.81      2400
weighted avg       0.81      0.81      0.81      2400



using word to vec


In [127]:
words = []
for sent in X:
    words.append(word_tokenize(sent))


In [128]:
words

[['jace',
  'rankin',
  'may',
  'short',
  'nothing',
  'mess',
  'man',
  'hauled',
  'saloon',
  'undertaker',
  'know',
  'famous',
  'bounty',
  'hunter',
  'oregon',
  '1890s',
  'shot',
  'man',
  'saloon',
  'finished',
  'year',
  'long',
  'quest',
  'avenge',
  'sister',
  'murder',
  'trying',
  'figure',
  'next',
  'snotty',
  'nosed',
  'farm',
  'boy',
  'rescued',
  'gang',
  'bully',
  'offer',
  'money',
  'kill',
  'man',
  'forced',
  'ranch',
  'reluctantly',
  'agrees',
  'bring',
  'man',
  'justice',
  'kill',
  'outright',
  'first',
  'need',
  'tell',
  'sister',
  'widower',
  'news',
  'kyla',
  'kyle',
  'springer',
  'bailey',
  'riding',
  'trail',
  'sleeping',
  'ground',
  'past',
  'month',
  'trying',
  'find',
  'jace',
  'want',
  'revenge',
  'man',
  'killed',
  'husband',
  'took',
  'ranch',
  'amongst',
  'crime',
  'keen',
  'detour',
  'jace',
  'want',
  'take',
  'realizes',
  'option',
  'hide',
  'behind',
  'boy',
  'persona',
  'best

In [129]:
w2v_model = Word2Vec(words,epochs=10)

In [130]:
words[0]

['jace',
 'rankin',
 'may',
 'short',
 'nothing',
 'mess',
 'man',
 'hauled',
 'saloon',
 'undertaker',
 'know',
 'famous',
 'bounty',
 'hunter',
 'oregon',
 '1890s',
 'shot',
 'man',
 'saloon',
 'finished',
 'year',
 'long',
 'quest',
 'avenge',
 'sister',
 'murder',
 'trying',
 'figure',
 'next',
 'snotty',
 'nosed',
 'farm',
 'boy',
 'rescued',
 'gang',
 'bully',
 'offer',
 'money',
 'kill',
 'man',
 'forced',
 'ranch',
 'reluctantly',
 'agrees',
 'bring',
 'man',
 'justice',
 'kill',
 'outright',
 'first',
 'need',
 'tell',
 'sister',
 'widower',
 'news',
 'kyla',
 'kyle',
 'springer',
 'bailey',
 'riding',
 'trail',
 'sleeping',
 'ground',
 'past',
 'month',
 'trying',
 'find',
 'jace',
 'want',
 'revenge',
 'man',
 'killed',
 'husband',
 'took',
 'ranch',
 'amongst',
 'crime',
 'keen',
 'detour',
 'jace',
 'want',
 'take',
 'realizes',
 'option',
 'hide',
 'behind',
 'boy',
 'persona',
 'best',
 'try',
 'keep',
 'pace',
 'confrontation',
 'along',
 'way',
 'get',
 'shot',
 'jace'

In [131]:
def avgword2vec(doc):
    # Filter words that are in the model's vocabulary
    vectors = [w2v_model.wv[word] for word in doc if word in w2v_model.wv.index_to_key]
    if len(vectors) > 0:
        return np.mean(vectors, axis=0)  # Compute mean along the correct axis
    else:
        return np.zeros(w2v_model.vector_size)  # Return a zero vector if no words are found

# Assuming `words` is a list of tokenized documents
X_w2v = []
for i in tqdm(range(len(words))):
    X_w2v.append(avgword2vec(words[i]))

# Convert X to a numpy array for further processing
X_w2v = np.array(X_w2v)

100%|██████████| 12000/12000 [00:17<00:00, 692.18it/s]


In [132]:
len(X_w2v)

12000

In [150]:
X_w2v.shape

(12000, 100)

In [173]:
X_w2v[10].reshape(1,-1).shape

(1, 100)

In [134]:
df.shape

(12000, 2)

In [152]:
w2v_df = pd.DataFrame()
for i in range(0,len(X_w2v)):
    d = pd.DataFrame(X_w2v[i].reshape(1,-1))
    w2v_df = pd.concat([w2v_df,d],ignore_index=True)

In [153]:
w2v_df.shape

(12000, 100)

In [154]:
w2v_df.head()

0         1         2         3         4         5         6   \
0 -0.042568 -0.035972 -0.114842 -0.009764  0.029842 -0.188634  0.128960   
1 -0.226000  0.162421 -0.260408  0.148270 -0.267017  0.010993  0.342018   
2  0.099890  0.321446 -0.052143  0.162522 -0.294972 -0.000362  0.272665   
3  0.233125  0.168253 -0.170560 -0.134217  0.110516 -0.100243  0.465417   
4 -0.041680 -0.088537 -0.075932  0.124251 -0.024830 -0.620993  0.045937   

         7         8         9   ...        90        91        92        93  \
0  0.422618 -0.340603 -0.351846  ...  0.186996 -0.009380 -0.081090  0.183506   
1  0.335383 -0.040408 -0.444571  ...  0.768738  0.152656 -0.282314 -0.204496   
2  0.316025 -0.080343 -0.152969  ...  0.432505  0.171690  0.074691  0.003542   
3  0.446423  0.249994  0.103236  ...  0.168051  0.183066  0.265787 -0.341804   
4  0.373245 -0.399378  0.234759  ...  0.718877  0.302432 -0.153876 -0.284096   

         94        95        96        97        98        99  
0  0.285258  0.264733  0.048298 -0.237696  0.009533 -0.335479  
1  0.001384  0.773511 -0.070907  0.091692 -0.722325 -0.545419  
2  0.275498  0.384816 -0.119327 -0.063503 -0.295211 -0.365192  
3  0.290365 -0.011916  0.260209  0.157788 -0.357666 -0.274274  
4  0.406329  0.447478  0.218170 -0.170839 -0.061229 -0.188596  

[5 rows x 100 columns]

In [157]:
X_word2vec = w2v_df
y_word2vec = y

In [159]:
from sklearn.model_selection import train_test_split
X_train_w2v, X_test_w2v, y_train_w2v , y_test_w2v = train_test_split(X_word2vec,y_word2vec,test_size=0.20)

In [162]:
from sklearn.naive_bayes import GaussianNB

In [163]:
gnb_w2v = GaussianNB().fit(X_train_w2v,y_train_w2v)

In [164]:
y_pred_w2v = gnb_w2v.predict(X_test_w2v)

In [165]:
print(accuracy_score(y_pred_w2v,y_test_w2v))
print(confusion_matrix(y_pred_w2v,y_test_w2v))
print(classification_report(y_pred_w2v,y_test_w2v))

0.7558333333333334
[[972 339]
 [247 842]]
              precision    recall  f1-score   support

           0       0.80      0.74      0.77      1311
           1       0.71      0.77      0.74      1089

    accuracy                           0.76      2400
   macro avg       0.76      0.76      0.76      2400
weighted avg       0.76      0.76      0.76      2400

